import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"

# cmd0 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  joint  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10   --no_maximal_plasticity_search'

#The basic model uses the same model for base_training_adam
cmd1 = 'py  ../framework/main.py small_VGG9_cl_128_128  --runmode first_task_basemodel_dump --gridsearch_name base_training_adam_ReloadOp_SH --method_name SI --ds_name tiny   --num_epochs 50  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001  --num_class 10  --no_maximal_plasticity_search --hyperparams 0'

cmd2 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  FT  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search'

cmd3 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search'

cmd4 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  EWC  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.05 --num_class 10  --no_maximal_plasticity_search'

cmd5 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  LWF  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search'

cmd6 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  MAS --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10   --no_maximal_plasticity_search'

cmd7 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  meanIMM --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1 --seed 7  --first_task_basemodel_folder  first_task_base_training_adam  --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search' #Methods Line 819 No_fremework True

cmd8 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  modeIMM --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1 --seed 7  --first_task_basemodel_folder  first_task_base_training_adam  --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search'

cmd9 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  EBLL  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10 --no_maximal_plasticity_search'

# cmd10 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH --method_name  IT  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --drop_margin 0.5 --no_maximal_plasticity_search'

cmd10 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat2 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --stochastic --seed 1'
cmd11 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat3 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 1'
cmd12 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat4 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 1 --stochastic --seed 3'
cmd13 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat5 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1'
cmd14 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat6 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 4'
cmd15 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat7 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0'
cmd16 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat8 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 4'
cmd17 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat9 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 1'
cmd18 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat10 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 2'
cmd19 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat11 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 3'
cmd20 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat12 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 1'
cmd21 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat13 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 2'
cmd22 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat14 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 3'
cmd23 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat15 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 6'
cmd24 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat16 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0.1 --stochastic --seed 7'

cmd30 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat30 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 6'
cmd31 = 'py ../framework/main.py small_VGG9_cl_128_128  --gridsearch_name base_training_adam_ReloadOp_SH_reweight_repeat31 --method_name  SI  --ds_name tiny   --test  --test_overwrite_mode --num_epochs 50 --n_iters 1  --first_task_basemodel_folder  first_task_base_training_adam --optimizer 1  --fixed_init_lr 0.001 --num_class 10  --no_maximal_plasticity_search --hyperparams 0 --stochastic --seed 7'
# cmds = [cmd2, cmd3, cmd4, cmd5, cmd6, cmd7, cmd8, cmd9]
#cmds = [cmd10, cmd11, cmd12, cmd13]
# cmds = [cmd14, cmd15, cmd16]
# cmds = [cmd17, cmd18, cmd19, cmd20, cmd21, cmd22]
cmds = [cmd10, cmd11, cmd12, cmd13, cmd14, cmd15, cmd16, cmd17, cmd18, cmd19, cmd20, cmd21, cmd22, cmd23, cmd24, cmd30, cmd31]
for cmd in cmds:
 os.system(cmd)

